#page title
page_title                                : Digital Flower Live Wallpaper             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
android_app_id                            : com.funparadigm.warpedflowerwallpaper.AnimatedFlowerWallpaper # Required. Enter android app ID to automatically populate name, price and icons (e.g. com.org.app).
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.funparadigm.warpedflowerwallpaper.AnimatedFlowerWallpaper # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/warped_flower_icon.jpg             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Digital Flower Live Wallpaper             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A digital flower Live Wallpaper fully configurable

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Stephane Cuillerdier                                
your_link                                 : https://aiekick.github.io/DigitalFlower                                               
email_address                             : aiekick@funparadigm.com
facebook_username                         :                                           
instagram_username                        : aiekick
twitter_username                          : aiekick
github_username                           : aiekick
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Animated Wallpaper
    description                           : Animated and colorful in background, Real Time (Depends of your GPU)
    fontawesome_icon_name                 : magic
    
  - title                                 : Fully Tunable
    description                           : Many widgets available for change color, shape, movement
    fontawesome_icon_name                 : cog

  - title                                 : Requirements
    description                           : Need support of Opengl ES 3.0 and Live wallpaper
    fontawesome_icon_name                 : play-circle

  - title                                 : # Automatic Icon and Metadata
    description                           : # Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : # sync

  - title                                 : # Easy to Tweak
    description                           : # Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # adjust
  
  - title                                 : # Feature List
    description                           : # Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # star

  - title                                 : # Smart App Banner
    description                           : # Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : # arrow-alt-circle-down

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/bg_low.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#0dc07d"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cccccc"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#cccccc"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
